# Generated by Django 3.0.8 on 2020-10-30 19:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, null=True, populate_from='name'),
        ),
    ]
