# Generated by Django 3.0.8 on 2020-11-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0006_auto_20201128_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PLACED', 'Your Order Is Placed'), ('CANCELED', 'Your Order Is Canceled'), ('PACKED', 'Your Order Is Packed'), ('SHIPPED', 'Your Order Is Ready For Shipping')], max_length=15),
        ),
    ]
